name: Manual Sync from Private Repo

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4
        with:
          path: public

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: averkoc/lxprivate
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: private

      - name: Copy 'docs/' folder from private to public
        run: |
          mkdir -p public/docs
          # rsync -av --delete private/docs/ public/docs/
          # The upper is old strict mirror version: overwrites public with private and deletes extra files
          rsync -av --update private/docs/ public/docs/

      - name: Configure Git
        run: |
          cd public
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd public
          git add docs
          if ! git diff --cached --quiet; then
            git commit -m "Sync docs folder from lxprivate"
            git push https://x-access-token:${TOKEN}@github.com/averkoc/lx.git HEAD:main
          else
            echo "No changes to commit."
          fi
